#!/bin/sh

if test -z "`autoconf --version 2>&1|head -n 1|egrep '2.5'`"; then
	echo "Autoconf 2.50+ is required. Aborting build...";
    exit 1;
fi

if test -z "`automake --version 2>&1|head -n 1|egrep '1.[89]'`"; then
	echo "Automake 1.8+ is required. Aborting build...";
	exit 1;
fi

if test -z "`libtool --version 2>&1|head -n 1|egrep '1.5'`"; then
	echo "Libtool 1.5+ is required. Aborting build...";
	exit 1;
fi

libtoolize --force --copy && aclocal && autoheader && automake --include-deps --add-missing --copy && autoconf 
